name: cross_picker
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.3+4
  universal_html: ^1.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: